# Generated by Django 5.2.8 on 2026-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_visible_in_api',
            field=models.BooleanField(default=True),
        ),
    ]
