# Generated by Django 5.2.8 on 2026-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_identity_is_visible_in_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='context_domain',
            field=models.CharField(choices=[('professional', 'Professional'), ('academic', 'Academic'), ('gaming', 'Gaming'), ('social', 'Social'), ('personal', 'Personal'), ('other', 'Other')], default='personal', help_text='Context in which this identity is intended to be used', max_length=32),
        ),
    ]
